version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ledgr-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ledgr
      POSTGRES_PASSWORD: ledgr
      POSTGRES_DB: ledgr
    ports:
      - "5432:5432"
    volumes:
      - ledgr-data:/var/lib/postgresql/data

volumes:
  ledgr-data:
